name: unit_test
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.14.3 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^1.0.0
  mocktail: ^0.2.0
  test: ^1.18.2
